# Generated by Django 3.2.9 on 2021-11-12 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128, verbose_name='position_for_which_election_is_conducted')),
                ('deadline', models.DateTimeField(verbose_name='deadline_for_the_election')),
                ('start_date', models.DateTimeField(verbose_name='start_date_of_the_election')),
                ('end_date', models.DateTimeField(verbose_name='end_date_of_the_election')),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_nomination', models.IntegerField(choices=[(1, 'Candidate'), (2, 'Voter')])),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
