# Generated by Django 3.2.9 on 2021-11-23 10:59

from django.db import migrations, models
import django.db.models.deletion
import elections.validators


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20211123_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='elections.nomination', validators=[elections.validators.validate_campaign_time, elections.validators.validate_candidate_nomination]),
        ),
    ]
