# Generated by Django 3.2.9 on 2021-11-25 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0003_alter_campaign_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='vote_count',
            field=models.JSONField(default={}, verbose_name='dict_of_vote_count'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='sha_512_256_generated_hash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL, verbose_name='Candidate')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.election', verbose_name='Election')),
                ('voter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL, verbose_name='Voter')),
            ],
        ),
    ]
