# Generated by Django 3.2.9 on 2021-11-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20211125_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='vote_count',
            field=models.JSONField(default=dict, verbose_name='dict_of_vote_count'),
        ),
    ]
