# Generated by Django 3.2.9 on 2021-11-12 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211107_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name_of_the_user')),
                ('about_me', models.TextField(max_length=65535, verbose_name='explain_about_yourself')),
                ('experience', models.TextField(max_length=65535, verbose_name='any_relevant_experience')),
                ('social_profile', models.URLField(blank=True, max_length=255, null=True, verbose_name='link_to_any_social_profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
